[
   {
      "type":"team",
      "handle":"Giants",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"hUheNZ9ZdI"
      }
   },
   {
      "type":"team",
      "handle":"Eagles",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"SgQJ0JEXmW"
      }
   },
   {
      "type":"team",
      "handle":"jaguars",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"E3I8791BcY"
      }
   },
   {
      "type":"team",
      "handle":"Panthers",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"0r7QTlKjSz"
      }
   },
   {
      "type":"team",
      "handle":"ChicagoBears",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"KdtXrkVJYD"
      }
   },
   {
      "type":"team",
      "handle":"Lions",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"9Ks4p9SjXH"
      }
   },
   {
      "type":"team",
      "handle":"49ers",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"gxH9VisZtW"
      }
   },
   {
      "type":"team",
      "handle":"Browns",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"CbLiVwKJQn"
      }
   },
   {
      "type":"team",
      "handle":"Redskins",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"r8V06K5Q0y"
      }
   },
   {
      "type":"team",
      "handle":"TBBuccaneers",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"QTY343kHgP"
      }
   },
   {
      "type":"team",
      "handle":"packers",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"NGGxWNz49V"
      }
   },
   {
      "type":"team",
      "handle":"KCChiefs",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"Sq9bFKkpOE"
      }
   },
   {
      "type":"team",
      "handle":"Saints",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"r5lm5Zj5nN"
      }
   },
   {
      "type":"team",
      "handle":"Patriots",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"ZeVrDmpJJI"
      }
   },
   {
      "type":"team",
      "handle":"OfficialEagles",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"SgQJ0JEXmW"
      }
   },
   {
      "type":"team",
      "handle":"Vikings",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"U6nhChk7pY"
      }
   },
   {
      "type":"team",
      "handle":"buffalobills",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"B8Ey6igDON"
      }
   },
   {
      "type":"team",
      "handle":"CowboysDotCom",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"hd9Calfg9l"
      }
   },
   {
      "type":"team",
      "handle":"Bengals",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"cI46vd7978"
      }
   },
   {
      "type":"team",
      "handle":"STLouisRams",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"C2z9rYY5yW"
      }
   },
   {
      "type":"team",
      "handle":"Seahawks",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"WMkfgOBMsO"
      }
   },
   {
      "type":"team",
      "handle":"Ravens",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"zrYkEbBnpR"
      }
   },
   {
      "type":"team",
      "handle":"MiamiDolphins",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"2rNMwy3lpJ"
      }
   },
   {
      "type":"team",
      "handle":"steelers",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"r76wtyjscA"
      }
   },
   {
      "type":"league",
      "handle":"nfl",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":""
      }
   },
   {
      "type":"team",
      "handle":"TennesseeTitans",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"RqbLb6y9Fy"
      }
   },
   {
      "type":"team",
      "handle":"Broncos",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"5J89RseKJH"
      }
   },
   {
      "type":"team",
      "handle":"HoustonTexans",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"YNX0KdO1ze"
      }
   },
   {
      "type":"team",
      "handle":"nyjets",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"w06ksyuKLr"
      }
   },
   {
      "type":"team",
      "handle":"Atlanta_Falcons",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"J4rBEpxQop"
      }
   },
   {
      "type":"team",
      "handle":"RAIDERS",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"BL5L4TaPED"
      }
   },
   {
      "type":"team",
      "handle":"chargers",
      "teamId":{
         "__type":"Pointer",
         "className":"Team",
         "objectId":"w6Zrho5XzJ"
      }
   }
]